x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  image: tmd-tcct-pipeline:latest  # Forces Docker to build ONE image and reuse it
  volumes:
    - ./data:/app/data
    - ./logs:/app/logs
  environment:
    - PYTHONUNBUFFERED=1
  tty: true
  stdin_open: true

services:
  extract:
    <<: *common-config
    profiles:
      - extract
    entrypoint: ["python", "preprocess.py", "--extract"]

  clean:
    <<: *common-config
    profiles:
      - clean
    entrypoint: ["python", "preprocess.py", "--clean"]

  preprocess:
    <<: *common-config
    profiles:
      - preprocess
    entrypoint: ["python", "preprocess.py", "--all"]